// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plxrmxzxywaucdvtazmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBseHJteHp4eXdhdWNkdnRhem13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2Njk5NzMsImV4cCI6MjA3NzI0NTk3M30.4kOWZTpw_pRV3-jdljN6wdFcAmNeR6RCvuXVWHlTSFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});